### ISSUE TITLE
Publish legal info of Docker images to DockerHub

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/knowledge-agents#22]
## Description

The legal info for the used Docker base images has been added via #21. 
Another mandatory step is missing though. This info also has to be published to the DockerHub page related to the image.
This can be achieved, when adding an action step like in the example workflow provided in [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05)

Extracted from that example:

```yaml
     # https://github.com/peter-evans/dockerhub-description
      # Important step to push image description to DockerHub 
      - name: Update Docker Hub description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
        # readme-filepath defaults to toplevel README.md, Only necessary if you have a dedicated file with your 'Notice for docker images'   
        # readme-filepath: path/to/dedicated/notice-for-docker-image.md 
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
```

Since this repository does contain multiple Dockerfiles and notices, the `readme-filepath` setting is needed

related to #5
